export { Main } from "./Main/Main";
export { FAQ } from "./FAQ/FAQ";
export { Translate } from "./Translate/Translate";
export { PlayGame } from "./PlayGame/PlayGame";
export { Options } from "./Options/Options";
export { Timer } from "./Timer/Timer";
export { OnBoarding } from "./OnBoarding/OnBoarding";
export { Packs } from "./Packs/Packs";
export { WordScreen } from "./WordScreen/WordScreen";
